# Generated by Django 4.0.5 on 2022-06-16 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('Created_date', models.DateTimeField(default=datetime.datetime.today)),
                ('Published_date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
    ]
